"""empty message

Revision ID: a415c6a1e54d
Revises: f69b971b25e0
Create Date: 2020-10-13 13:43:46.630707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a415c6a1e54d'
down_revision = 'f69b971b25e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rocket_data', sa.Column('vertical_velocity_IMU', sa.Float(), nullable=True))
    op.drop_column('rocket_data', 'vertical_acceleration_units')
    op.drop_column('rocket_data', 'temperature_units')
    op.drop_column('rocket_data', 'altitude_units')
    op.drop_column('rocket_data', 'vertical_velocity_units')
    op.drop_column('rocket_data', 'pressure_units')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rocket_data', sa.Column('pressure_units', sa.VARCHAR(), nullable=True))
    op.add_column('rocket_data', sa.Column('vertical_velocity_units', sa.VARCHAR(), nullable=True))
    op.add_column('rocket_data', sa.Column('altitude_units', sa.VARCHAR(), nullable=True))
    op.add_column('rocket_data', sa.Column('temperature_units', sa.VARCHAR(), nullable=True))
    op.add_column('rocket_data', sa.Column('vertical_acceleration_units', sa.VARCHAR(), nullable=True))
    op.drop_column('rocket_data', 'vertical_velocity_IMU')
    # ### end Alembic commands ###
