"""init

Revision ID: bb79a49240f3
Revises: 
Create Date: 2020-10-12 19:49:05.453810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb79a49240f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('home_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_home_data_timestamp'), 'home_data', ['timestamp'], unique=False)
    op.create_table('rocket_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acceleration_x', sa.Float(), nullable=True),
    sa.Column('acceleration_y', sa.Float(), nullable=True),
    sa.Column('acceleration_z', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('pressure_units', sa.String(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('temperature_units', sa.String(), nullable=True),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('altitude_units', sa.String(), nullable=True),
    sa.Column('vertical_velocity', sa.Float(), nullable=True),
    sa.Column('vertical_velocity_units', sa.String(), nullable=True),
    sa.Column('vertical_acceleration', sa.Float(), nullable=True),
    sa.Column('vertical_acceleration_units', sa.String(), nullable=True),
    sa.Column('airbrakes_state', sa.Binary(), nullable=True),
    sa.Column('flight_state', sa.Integer(), nullable=True),
    sa.Column('time_milliseconds', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rocket_data_time_milliseconds'), 'rocket_data', ['time_milliseconds'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rocket_data_time_milliseconds'), table_name='rocket_data')
    op.drop_table('rocket_data')
    op.drop_index(op.f('ix_home_data_timestamp'), table_name='home_data')
    op.drop_table('home_data')
    # ### end Alembic commands ###
