"""Removed unit columns

Revision ID: f69b971b25e0
Revises: bb79a49240f3
Create Date: 2020-10-13 13:13:42.678774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f69b971b25e0'
down_revision = 'bb79a49240f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rocket_data', 'vertical_acceleration_units')
    op.drop_column('rocket_data', 'altitude_units')
    op.drop_column('rocket_data', 'temperature_units')
    op.drop_column('rocket_data', 'pressure_units')
    op.drop_column('rocket_data', 'vertical_velocity_units')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rocket_data', sa.Column('vertical_velocity_units', sa.VARCHAR(), nullable=True))
    op.add_column('rocket_data', sa.Column('pressure_units', sa.VARCHAR(), nullable=True))
    op.add_column('rocket_data', sa.Column('temperature_units', sa.VARCHAR(), nullable=True))
    op.add_column('rocket_data', sa.Column('altitude_units', sa.VARCHAR(), nullable=True))
    op.add_column('rocket_data', sa.Column('vertical_acceleration_units', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
